// Question flow definition for the Garden Shed path.
const QUESTIONS = [
  { id: "projectType", prompt: "Hi! I'm your home-project designer. What are we building today?", hint: "I'll walk us through the garden shed flow in detail.", kind: "choice", options: [ { value: "shed", label: "Garden shed", meta: "Walked-through demo" }, { value: "pergola", label: "Pergola", meta: "Sketch only" }, { value: "planter", label: "Raised planter beds", meta: "Sketch only" }, { value: "arbor", label: "Garden arbor", meta: "Sketch only" }, ], default: "shed" },
  { id: "purpose", prompt: "What's it for, mostly?", hint: "This changes what goes inside and how wide the doors are.", kind: "choice", options: [ { value: "tools", label: "Tool & lawn storage", meta: "Pegboards, mower bay" }, { value: "garden", label: "Potting + garden workspace", meta: "Bench, light" }, { value: "retreat", label: "Backyard retreat", meta: "Window, finished inside" }, { value: "mixed", label: "A mix of all three", meta: "Flexible layout" } ], default: "tools" },
  { id: "size", prompt: "How big should it be?", hint: "Most DIY sheds live between 8x8 and 12x16.", kind: "size", default: { w: 10, d: 12 } },
  { id: "roof", prompt: "Pick a roof style.", kind: "roof", options: [ { value: "gable", label: "Gable", note: "Classic, easy to frame" }, { value: "saltbox", label: "Saltbox", note: "Charming asymmetry" }, { value: "lean-to", label: "Lean-to", note: "Simplest, against a wall" }, { value: "hip", label: "Hip", note: "Wind-resistant" } ], default: "gable" },
  { id: "siding", prompt: "How about siding?", kind: "material", options: [ { value: "t1-11", label: "T1-11 plywood", price: 2.1, life: "15-20 yr", note: "DIY-friendly, paint required" }, { value: "cedar", label: "Cedar shiplap", price: 5.8, life: "30+ yr", note: "Beautiful, weathers gray" }, { value: "lp-smart", label: "LP SmartSide", price: 3.2, life: "25-30 yr", note: "Engineered, very forgiving" }, { value: "vinyl", label: "Vinyl", price: 2.6, life: "20-25 yr", note: "Low maintenance" } ], default: "lp-smart" },
  { id: "door", prompt: "Door setup?", kind: "choice", options: [ { value: "single", label: "Single 36\" door", meta: "Walk-in access" }, { value: "double", label: "Double 60\" barn doors", meta: "Fits a mower" }, { value: "dutch", label: "Dutch door", meta: "Charming, ventilates" } ], default: "double" },
  { id: "windows", prompt: "Windows?", kind: "choice", options: [ { value: 0, label: "None", meta: "Max wall space" }, { value: 1, label: "One side window", meta: "Daylight on bench" }, { value: 2, label: "Two windows", meta: "Cross-ventilation" }, { value: 4, label: "Four (retreat vibe)", meta: "Airy, finished feel" } ], default: 2 },
  { id: "foundation", prompt: "Foundation?", hint: "This is the #1 thing that decides how long your shed lasts.", kind: "choice", options: [ { value: "skid", label: "Skid / gravel pad", meta: "DIY, movable, most common" }, { value: "pier", label: "Concrete piers", meta: "Uneven ground, longer life" }, { value: "slab", label: "Concrete slab", meta: "Permanent, permit usually required" } ], default: "skid" },
  { id: "budget", prompt: "What's your budget looking like?", kind: "budget", default: "mid", options: [ { value: "lean", label: "Lean", range: "$1.2k-$2.5k" }, { value: "mid", label: "Comfortable", range: "$2.5k-$5k" }, { value: "nice", label: "Treat yourself", range: "$5k-$9k" } ] },
  { id: "skill", prompt: "How handy are you?", kind: "skill", default: "some", options: [ { value: "new", label: "First real build", icon: "🌱" }, { value: "some", label: "I own a miter saw", icon: "🔨" }, { value: "pro", label: "I've framed before", icon: "🏗" } ] },
];
window.QUESTIONS = QUESTIONS;
